### PR TITLE
Feature/devcontainer

### PR DESCRIPTION
**Pull request by leaver2000**

### CODE REVIEW

**Comment by tjlang** [comment]
Thanks for the pull request! Could you provide a bit more context on it? It looks like you are changing over from basemap to cartopy (something long needed to keep the code relevant), and I wanted to know a bit more about the development container approach. Thanks again!

**Comment by leaver2000** [comment]
> Thanks for the pull request! Could you provide a bit more context on it? It looks like you are changing over from basemap to cartopy (something long needed to keep the code relevant), and I wanted to know a bit more about the development container approach. Thanks again!

Yeah! Visual Studio Code gives you the ability to create a container and connect to it using the [remote-container](https://code.visualstudio.com/docs/remote/containers) extension.  To get started with it.

Install docker and visual studio code. In VSC install and enable the remote-container extension.  Then press `ctrl + shift +p` and select `open folder in container`


Cartopy is kind of a pain to install outside of a anaconda environment because of it's dependencies on the [osgeo](https://www.osgeo.org/) libs `PROJ GEOS GDAL`.  In this development container I am using a Ubuntu 22.04 base image from the Microsoft registry and python3.10.  

The docker file has 3 stages:
`base` - used in the final and has runtime requirements. 
`builder` - which creates the virtual environment with other tools needed to compile Cartopy along with several other python packages.
`final` - pulls the venv from the `builder` and sets a non root user to avoid conflicts with the host system.

The `.devcontainer.json` adds some `vscode` extensions I use frequently and establishes `PATH` & `PYTHONPATH`

**Comment by leaver2000** [comment]
I'm interested in updating more of the code base as well, but I figured this is sort of a good starting point.  Establishing the development environment.

I think before I start to move the codebase away from basemap I wanted to write up some unit tests.  To make sure I don't break anything in the process.

**Comment by tjlang** [comment]
OK, thanks again for doing this, I am going to merge.

**Comment by leaver2000** [comment]
Thanks for the merge TJ. 

I wanted to run something else by you, id like to bring the entire repo up to date, preferably python 3.7+ for the inclusion of dataclasses and type hints. 

This would result in breaking changes for older versions of python. That being said are you interested in a 2.0 release? 

I've been working with some CUDA/dask based docker containers to leverage gpu/multi-core support which significantly increases performance.

**Comment by tjlang** [comment]
Yes, this would be welcomed. OK to break for Python 2. The software needs to become Python 3 compliant to remain viable. Thanks!

**Pull request merged**
